name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - run: "./gradlew test"

  publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - run: "./gradlew publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
